apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      imagePullSecrets:
        - name: countly-registry
      containers:
      - name: python
        image:  gcr.io/first-project-2030/fathalla22/myapp:v1
        env:
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_HOST
          value: redis
        ports:
        - containerPort: 80
